export const manufacturers = [
  "Acura",
  "Alfa Romeo",
  "Aston Martin",
  "Audi",
  "Bentley",
  "BMW",
  "Buick",
  "Cadillac",
  "Chevrolet",
  "Chrysler",
  "Citroen",
  "Dodge",
  "Ferrari",
  "Fiat",
  "Ford",
  "GMC",
  "Honda",
  "Hyundai",
  "Infiniti",
  "Jaguar",
  "Jeep",
  "Kia",
  "Lamborghini",
  "Land Rover",
  "Lexus",
  "Lincoln",
  "Maserati",
  "Mazda",
  "McLaren",
  "Mercedes-Benz",
  "MINI",
  "Mitsubishi",
  "Nissan",
  "Porsche",
  "Ram",
  "Rolls-Royce",
  "Subaru",
  "Tesla",
  "Toyota",
  "Volkswagen",
  "Volvo",
];

export const yearsOfProduction = [
  { title: "Vuosimalli", value: "" },
  { title: "1900", value: "1900" },
  { title: "1910", value: "1910" },
  { title: "1920", value: "1920" },
  { title: "1930", value: "1930" },
  { title: "1940", value: "1940" },
  { title: "1950", value: "1950" },
  { title: "1960", value: "1960" },
  { title: "1970", value: "1970" },
  { title: "1980", value: "1980" },
  { title: "1981", value: "1981" },
  { title: "1982", value: "1982" },
  { title: "1983", value: "1983" },
  { title: "1984", value: "1984" },
  { title: "1985", value: "1985" },
  { title: "1986", value: "1986" },
  { title: "1987", value: "1987" },
  { title: "1988", value: "1988" },
  { title: "1989", value: "1989" },
  { title: "1990", value: "1990" },
  { title: "1991", value: "1991" },
  { title: "1992", value: "1992" },
  { title: "1993", value: "1993" },
  { title: "1994", value: "1994" },
  { title: "1995", value: "1995" },
  { title: "1996", value: "1996" },
  { title: "1997", value: "1997" },
  { title: "1998", value: "1998" },
  { title: "1999", value: "1999" },
  { title: "2000", value: "2000" },
  { title: "2001", value: "2001" },
  { title: "2002", value: "2002" },
  { title: "2003", value: "2003" },
  { title: "2004", value: "2004" },
  { title: "2005", value: "2005" },
  { title: "2006", value: "2006" },
  { title: "2007", value: "2007" },
  { title: "2008", value: "2008" },
  { title: "2009", value: "2009" },
  { title: "2010", value: "2010" },
  { title: "2011", value: "2011" },
  { title: "2012", value: "2012" },
  { title: "2013", value: "2013" },
  { title: "2014", value: "2014" },
  { title: "2015", value: "2015" },
  { title: "2016", value: "2016" },
  { title: "2017", value: "2017" },
  { title: "2018", value: "2018" },
  { title: "2019", value: "2019" },
  { title: "2020", value: "2020" },
  { title: "2021", value: "2021" },
  { title: "2022", value: "2022" },
  { title: "2023", value: "2023" },
  { title: "2024", value: "2024" },
  { title: "2025", value: "2025" },
];

export const fuels = [
  {title: "Käyttövoima", value: "",},
  {title: "Bensiini", value: "Bensiini",},
  {title: "Diesel", value: "Diesel",},
  {title: "E85/bensiini", value: "E85/bensiini",},
  {title: "Hybridi", value: "Hybridi",},
  {title: "Hybridi (bensiini/sähkö)", value: "Hybridi (bensiini/sähkö)",},
  {title: "Hybridi (diesel/sähkö)", value: "Hybridi (diesel/sähkö)",},
  {title: "Kaasu", value: "Kaasu",},
  {title: "Sähkö", value: "Sähkö",},

];

export const vaihteisto = [
  { title: "Tyyppi", value: "" },
  { title: "Henkilöauto", value: "Henkilöauto" },
  { title: "Kevyt kuorma-auto", value: "Kevyt kuorma-auto" },
  { title: "Minibussi", value: "Minibussi" },
  { title: "Pakettiauto", value: "Pakettiauto" },

]
export const tyyppi = [
  { title: "Vaihteisto", value: "" },
  { title: "Automaatti", value: "Automaatti" },
  { title: "Manuaali", value: "Manuaali" },
]

export const korimalli = [
  { title: "Korimalli", value: "" },
  { title: "Avoauto", value: "Avoauto" },
  { title: "Avolava", value: "Avolava" },
  { title: "Coupé", value: "Coupé" },
  { title: "Erillinen kuormatila", value: "Erillinen kuormatila" },
  { title: "Farmari", value: "Farmari" },
  { title: "Jatko-ohjaamo", value: "Jatko-ohjaamo" },
  { title: "Kilpa-ajoneuvo", value: "Kilpa-ajoneuvo" },
  { title: "Lyhyt - Korkea", value: "Lyhyt - Korkea" },
  { title: "Lyhyt - Matala", value: "Lyhyt - Matala" },
  { title: "Lyhyt - Puolikorkea", value: "Lyhyt - Puolikorkea" },
  { title: "Maastoauto SUV", value: "Maastoauto SUV" },
  { title: "Muu", value: "Muu" },
  { title: "Pitkä - Korkea", value: "Pitkä - Korkea" },
  { title: "Pitkä - Matala", value: "Pitkä - Matala" },
  { title: "Pitkä - Puolikorkea", value: "Pitkä - Puolikorkea" },
  { title: "Porrasperä", value: "Porrasperä" },
  { title: "Puolipitkä - Korkea", value: "Puolipitkä - Korkea" },
  { title: "Puolipitkä - Matala", value: "Puolipitkä - Matala" },
  { title: "Puolipitkä - Puolikorkea", value: "Puolipitkä - Puolikorkea" },
  { title: "Tila-auto", value: "Tila-auto" },
  { title: "Viistoperä", value: "Viistoperä" },


]

export const footerLinks = [
  {
    title: "About",
    links: [
      { title: "How it works", url: "/" },
      { title: "Featured", url: "/" },
      { title: "Partnership", url: "/" },
      { title: "Bussiness Relation", url: "/" },
    ],
  },
  {
    title: "Company",
    links: [
      { title: "Events", url: "/" },
      { title: "Blog", url: "/" },
      { title: "Podcast", url: "/" },
      { title: "Invite a friend", url: "/" },
    ],
  },
  {
    title: "Socials",
    links: [
      { title: "Discord", url: "/" },
      { title: "Instagram", url: "/" },
      { title: "Twitter", url: "/" },
      { title: "Facebook", url: "/" },
    ],
  },
];
